title: "GRUPO OX"
description: "OX Industria de produtos quimicos"
permalink: ':title'
img: "https://picsum.photos/600/363" #https://picsum.photos/600/363
baseurl: "/"
url: "https://www.souox.com"
markdown: kramdown
# paginate: 10
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
